server:
  port: 8080

spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
        hbm2ddl:
          auto: update
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/ygt
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver